module.exports = {
  preset: 'react-native',
  collectCoverage: true,
  coveragePathIgnorePatterns: [
    "/node_modules/",
    "/styles/",
    "/themes/",
    "/interfaces/",
    "/assets/",
    "/__tests__/",
    "\\.d\\.ts$",
    "\\styles\\.(ts|tsx)$",
    "\\style\\.(ts|tsx)$",
    "types\\.(ts|tsx)$",
  ],
  collectCoverageFrom: [
    "src/**/*.{js,jsx,ts,tsx}",
    "!src/**/*styles.{ts,tsx}",
    "!src/**/*style.{ts,tsx}",
    "!src/**/styles.ts",
    "!src/styles/**/*",
    "!src/themes/**/*",
    "!src/interfaces/**/*",
    "!src/assets/**/*",
    "!src/**/*.types.{ts,tsx}",
    "!src/**/*.test.{ts,tsx}",
    "!src/**/__tests__/**/*",
    "!src/**/*.spec.{ts,tsx}",
    "!src/**/constants/*",
    "!src/**/constants.ts*",
    "!src/**/references.ts",
    "App.tsx",
  ],
};
